# Generated by Django 3.2.19 on 2024-04-23 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoeknaam', models.CharField(max_length=255)),
                ('bedrijfsnaam', models.CharField(max_length=255)),
                ('straat', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('plaats', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
                ('koordinaten', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Factuur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factuurnummer', models.CharField(editable=False, max_length=50)),
                ('factuurdatum', models.DateField()),
                ('verzenddatum', models.DateField()),
                ('betaaldatum', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BETAALD', 'Betaald'), ('VERVALLEN', 'Vervallen')], max_length=10)),
                ('annulering', models.BooleanField(default=False)),
                ('bedrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('btw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totaalbedrag', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoeknaam', models.CharField(max_length=255)),
                ('bedrijfsnaam', models.CharField(max_length=255)),
                ('FIN', models.CharField(max_length=50)),
                ('kontaktpersoon', models.CharField(max_length=255)),
                ('telefoon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(max_length=11)),
                ('betalingsvoorwaarden', models.TextField()),
                ('hoofdadres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturen.adres')),
            ],
        ),
        migrations.CreateModel(
            name='FactuurRegel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uitvoerdatum', models.DateField()),
                ('uitvoerreferentie', models.CharField(max_length=255)),
                ('opmerking', models.TextField(blank=True)),
                ('subbedrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regelbedrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factuur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regel_factuur', to='facturen.factuur')),
            ],
        ),
        migrations.AddField(
            model_name='factuur',
            name='klant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturen.klant'),
        ),
        migrations.AddField(
            model_name='factuur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Annulering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('reden', models.TextField()),
                ('volbedrag', models.BooleanField()),
                ('bedrag', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factuur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annulering_factuur', to='facturen.factuur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
