# Generated by Django 3.2.19 on 2024-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='koordinaten',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factuur',
            name='betaaldatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factuur',
            name='factuurdatum',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='factuur',
            name='verzenddatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
