# Generated by Django 5.0.4 on 2024-04-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturen', '0002_auto_20240424_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adressen'},
        ),
        migrations.AlterModelOptions(
            name='annulering',
            options={'verbose_name': 'Annulering', 'verbose_name_plural': 'Annuleringen'},
        ),
        migrations.AlterModelOptions(
            name='factuur',
            options={'verbose_name': 'Factuur', 'verbose_name_plural': 'Facturen'},
        ),
        migrations.AlterModelOptions(
            name='klant',
            options={'verbose_name': 'Klant', 'verbose_name_plural': 'Klanten'},
        ),
        migrations.AlterField(
            model_name='factuur',
            name='factuurdatum',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factuur',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('BETAALD', 'Betaald'), ('VERVALLEN', 'Vervallen')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='factuurregel',
            name='opmerking',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
